steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia.gcr.io/ssu-esc/music-player-backend:$COMMIT_SHA',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia.gcr.io/ssu-esc/music-player-backend:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'music-player-backend'
      - '--image'
      - 'asia.gcr.io/ssu-esc/music-player-backend:$COMMIT_SHA'
      - '--region'
      - 'ap-northeast-1'
      - '--platform'
      - 'managed'
images:
  - asia.gcr.io/ssu-esc/music-player-backend
